# Generated by Django 3.0 on 2020-10-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pareja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pareja1', models.CharField(blank=True, max_length=100, verbose_name='pareja1')),
                ('pareja2', models.CharField(blank=True, max_length=100, verbose_name='pareja2')),
            ],
            options={
                'verbose_name': 'pareja',
                'verbose_name_plural': 'parejas',
            },
        ),
    ]
