# Generated by Django 3.0 on 2020-10-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, verbose_name='nombre')),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='')),
                ('pelea', models.CharField(blank=True, max_length=100, verbose_name='pelea')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'lugar',
                'verbose_name_plural': 'lugares',
            },
        ),
    ]
