# Generated by Django 3.0 on 2020-10-10 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201009_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='imagen1',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='imagen2',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
