# Generated by Django 3.0 on 2020-10-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20201009_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='caballero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, verbose_name='nombre')),
                ('rango', models.CharField(blank=True, max_length=100, verbose_name='rango')),
                ('poder', models.CharField(blank=True, max_length=100, verbose_name='poder')),
                ('imagen', models.FileField(blank=True, null=True, upload_to='media/')),
            ],
            options={
                'verbose_name': 'caballero',
                'verbose_name_plural': 'caballeros',
            },
        ),
    ]
