# Generated by Django 3.0 on 2020-10-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_caballero'),
    ]

    operations = [
        migrations.CreateModel(
            name='pelea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peleador1', models.CharField(blank=True, max_length=100, verbose_name='peleador1')),
                ('peleador2', models.CharField(blank=True, max_length=100, verbose_name='peleador2')),
            ],
            options={
                'verbose_name': 'pelea',
                'verbose_name_plural': 'peleas',
            },
        ),
    ]
